export const categories = ["Emprendimiento", "Cultura", "Arte", "Turismo", "Educación", "Tecnología", "Gastronomía", "Comercio", "Industria", "Agro", "Moda", "Bienestar", "Impacto Social", "Deporte"];

export type Project = {
  id: number; name: string; slug: string; category: string; shortDescription: string; story: string; founderName: string; startYear: number; location: string; whatsapp: string; instagram: string; facebook?: string; website?: string; featured: boolean; mainImage: string; gallery: string[]; lat: number; lng: number; quote: string;
};

const image = (id: string) => `https://images.unsplash.com/${id}?auto=format&fit=crop&w=1200&q=80`;

export const projects: Project[] = [
  { id: 1, name: "Puerto Creativo Magdalena", slug: "puerto-creativo-magdalena", category: "Cultura", shortDescription: "Laboratorio ciudadano para formación audiovisual, memoria ribereña y producción cultural joven.", story: "Nació frente al río como un espacio para que jóvenes narren su barrio con cámaras, podcast y talleres de escritura. Hoy conecta colegios, artistas y gestores culturales para convertir memorias cotidianas en piezas editoriales que viajan por toda la ciudad.", founderName: "Laura Castaño", startYear: 2021, location: "Centro, La Dorada", whatsapp: "+573001112233", instagram: "@puertocreativomagdalena", website: "https://hechoenladorada.co", featured: true, mainImage: image("photo-1500530855697-b586d89ba3ee"), gallery: [image("photo-1492684223066-81342ee5ff30"), image("photo-1516280440614-37939bbacd81")], lat: 5.454, lng: -74.668, quote: "La cultura también se embarca en el puerto." },
  { id: 2, name: "Café Estación Dorada", slug: "cafe-estacion-dorada", category: "Gastronomía", shortDescription: "Café de origen caldense con menú local y noches de lectura junto a la antigua estación.", story: "Este café rescata conversaciones pausadas, recetas de abuelas y granos de productores de la región. Sus mesas se han convertido en punto de encuentro para viajeros, comerciantes y creadores.", founderName: "Andrés Ríos", startYear: 2019, location: "Barrio Las Ferias", whatsapp: "+573004445566", instagram: "@cafeestaciondorada", featured: true, mainImage: image("photo-1509042239860-f550ce710b93"), gallery: [image("photo-1442512595331-e89e73853f31"), image("photo-1495474472287-4d71bcdd2085")], lat: 5.451, lng: -74.662, quote: "Un café para conversar la ciudad." },
  { id: 3, name: "Ribera Bike Tours", slug: "ribera-bike-tours", category: "Turismo", shortDescription: "Rutas en bicicleta por paisajes ribereños, patrimonio urbano y miradores de atardecer.", story: "Un grupo de ciclistas diseñó recorridos seguros para mirar La Dorada con otros ojos. Cada ruta mezcla deporte, historia, comercio local y paradas gastronómicas.", founderName: "Natalia Gómez", startYear: 2020, location: "Malecón", whatsapp: "+573007778899", instagram: "@riberabiketours", featured: true, mainImage: image("photo-1485965120184-e220f721d03e"), gallery: [image("photo-1517649763962-0c623066013b"), image("photo-1500534314209-a25ddb2bd429")], lat: 5.459, lng: -74.671, quote: "Pedalear también es pertenecer." },
  { id: 4, name: "Aulas del Río", slug: "aulas-del-rio", category: "Educación", shortDescription: "Programa comunitario de refuerzo escolar, ciencia ciudadana y lectura en barrios ribereños.", story: "Voluntarios docentes y universitarios acompañan a niños y familias con clubes de lectura, experimentos sencillos y mentorías para proyectos de vida.", founderName: "Mónica Salazar", startYear: 2018, location: "Barrio Victoria Real", whatsapp: "+573009991122", instagram: "@aulasdelrio", featured: false, mainImage: image("photo-1509062522246-3755977927d7"), gallery: [image("photo-1497633762265-9d179a990aa6")], lat: 5.447, lng: -74.659, quote: "La educación fluye como el Magdalena." },
  { id: 5, name: "Mercado Verde La Dorada", slug: "mercado-verde-la-dorada", category: "Agro", shortDescription: "Red de productores rurales que vende canastas frescas y promueve consumo responsable.", story: "Conecta fincas cercanas con hogares y restaurantes. Cada entrega cuenta quién cultivó los alimentos y cómo apoyar economías campesinas.", founderName: "Jorge Ramírez", startYear: 2022, location: "Plaza de Mercado", whatsapp: "+573002224455", instagram: "@mercadoverdeladorada", featured: true, mainImage: image("photo-1488459716781-31db52582fe9"), gallery: [image("photo-1464226184884-fa280b87c399")], lat: 5.452, lng: -74.666, quote: "Comprar local también cultiva futuro." },
  { id: 6, name: "Taller Mangle Diseño", slug: "taller-mangle-diseno", category: "Moda", shortDescription: "Marca de prendas frescas inspiradas en el río, el puerto y oficios populares.", story: "Diseñadoras locales trabajan con costureras de barrio para crear piezas cómodas, durables y con estampados de identidad doradense.", founderName: "Camila Yepes", startYear: 2023, location: "Avenida de los Estudiantes", whatsapp: "+573005556677", instagram: "@tallermangle", featured: false, mainImage: image("photo-1496747611176-843222e1e57c"), gallery: [image("photo-1529139574466-a303027c1d8b")], lat: 5.456, lng: -74.664, quote: "Vestir el territorio con orgullo." },
  { id: 7, name: "Conecta Dorada Tech", slug: "conecta-dorada-tech", category: "Tecnología", shortDescription: "Comunidad de aprendizaje para programación, automatización y herramientas digitales.", story: "Reúne estudiantes, comerciantes y profesionales para resolver problemas locales con tecnología práctica y mentorías abiertas.", founderName: "Felipe Arango", startYear: 2021, location: "Biblioteca Municipal", whatsapp: "+573006667788", instagram: "@conectadoradatech", featured: true, mainImage: image("photo-1516321318423-f06f85e504b3"), gallery: [image("photo-1498050108023-c5249f4df085")], lat: 5.455, lng: -74.661, quote: "Innovar desde el puerto hacia el mundo." },
  { id: 8, name: "Casa Tambora", slug: "casa-tambora", category: "Arte", shortDescription: "Escuela independiente de percusión, danza y músicas del Magdalena Medio.", story: "La casa abre sus puertas para ensayos, muestras y procesos de iniciación artística con niños, jóvenes y adultos mayores.", founderName: "Óscar Molina", startYear: 2017, location: "Barrio Corea", whatsapp: "+573008889900", instagram: "@casatambora", featured: false, mainImage: image("photo-1514525253161-7a46d19cd819"), gallery: [image("photo-1460723237483-7a6dc9d0b212")], lat: 5.449, lng: -74.67, quote: "Donde suena el tambor, se reúne el barrio." },
  { id: 9, name: "Manos Doradas Fundación", slug: "manos-doradas-fundacion", category: "Impacto Social", shortDescription: "Acompañamiento a adultos mayores con alimentación, escucha y redes de cuidado.", story: "La fundación organiza jornadas barriales, rutas de apoyo y campañas de voluntariado para que nadie envejezca en soledad.", founderName: "Elena Patiño", startYear: 2016, location: "Barrio Renán Barco", whatsapp: "+573003331144", instagram: "@manosdoradas", featured: true, mainImage: image("photo-1544027993-37dbfe43562a"), gallery: [image("photo-1517048676732-d65bc937f952")], lat: 5.46, lng: -74.66, quote: "Cuidar también construye ciudad." },
  { id: 10, name: "Cancha Viva", slug: "cancha-viva", category: "Deporte", shortDescription: "Torneos formativos y escuelas deportivas con enfoque de convivencia.", story: "Entrenadores y familias recuperan espacios deportivos para formar disciplina, amistad y liderazgo en niñas y niños.", founderName: "Diego Sánchez", startYear: 2020, location: "Unidad Deportiva", whatsapp: "+573001234567", instagram: "@canchaviva", featured: false, mainImage: image("photo-1526232761682-d26e03ac148e"), gallery: [image("photo-1431324155629-1a6deb1dec8d")], lat: 5.444, lng: -74.663, quote: "La cancha también educa." },
  { id: 11, name: "La Ruta del Bocachico", slug: "la-ruta-del-bocachico", category: "Gastronomía", shortDescription: "Experiencia culinaria que conecta restaurantes tradicionales y relatos de pescadores.", story: "Una alianza de cocineras y guías locales diseña paradas para probar sabores ribereños y aprender del oficio pesquero.", founderName: "Rosa Beltrán", startYear: 2022, location: "Zona del Malecón", whatsapp: "+573004567890", instagram: "@rutadelbocachico", featured: true, mainImage: image("photo-1559847844-5315695dadae"), gallery: [image("photo-1543352634-a1c51d9f1fa7")], lat: 5.458, lng: -74.672, quote: "El río también se cuenta en la mesa." },
  { id: 12, name: "Editorial Puerto Sol", slug: "editorial-puerto-sol", category: "Cultura", shortDescription: "Sello independiente para publicar crónicas, fanzines y libros de autores locales.", story: "Imprime tirajes cortos, acompaña procesos de escritura y lleva lecturas a cafés, colegios y parques.", founderName: "Santiago Núñez", startYear: 2023, location: "Centro Cultural", whatsapp: "+573009876543", instagram: "@editorialpuertosol", featured: false, mainImage: image("photo-1495020689067-958852a7765e"), gallery: [image("photo-1519682337058-a94d519337bc")], lat: 5.453, lng: -74.665, quote: "Publicar para que la ciudad se lea." },
  { id: 13, name: "BioRibera Bienestar", slug: "bioribera-bienestar", category: "Bienestar", shortDescription: "Clases de yoga, caminatas conscientes y salud preventiva en espacios verdes.", story: "Promueve rutinas sencillas de autocuidado con profesionales locales y encuentros al amanecer cerca del río.", founderName: "Valentina Mora", startYear: 2021, location: "Parque Santander", whatsapp: "+573007654321", instagram: "@bioribera", featured: false, mainImage: image("photo-1506126613408-eca07ce68773"), gallery: [image("photo-1545389336-cf090694435e")], lat: 5.4525, lng: -74.6682, quote: "Respirar la ciudad con calma." },
  { id: 14, name: "Logística Puerto Norte", slug: "logistica-puerto-norte", category: "Industria", shortDescription: "Emprendimiento de soluciones logísticas para pequeños comerciantes del Magdalena Medio.", story: "Optimiza rutas, bodegaje y entregas para negocios que necesitan crecer sin perder cercanía con sus clientes.", founderName: "Hernán Mejía", startYear: 2020, location: "Zona Industrial", whatsapp: "+573002468135", instagram: "@puertonorte", featured: false, mainImage: image("photo-1494412651409-8963ce7935a7"), gallery: [image("photo-1586528116311-ad8dd3c8310d")], lat: 5.462, lng: -74.655, quote: "Mover productos, mover oportunidades." },
  { id: 15, name: "Comercio Vivo Centro", slug: "comercio-vivo-centro", category: "Comercio", shortDescription: "Red de tiendas familiares que crea vitrinas colectivas, rutas de compra y campañas locales.", story: "Comerciantes del centro se unieron para mejorar servicio, contar historias de sus locales y fortalecer compras de cercanía.", founderName: "Patricia León", startYear: 2019, location: "Centro Comercial Abierto", whatsapp: "+573001357924", instagram: "@comerciovivocentro", featured: true, mainImage: image("photo-1441986300917-64674bd600d8"), gallery: [image("photo-1472851294608-062f824d29cc")], lat: 5.4546, lng: -74.6665, quote: "Cada vitrina guarda una historia." }
];

export const stories = Array.from({ length: 10 }, (_, index) => {
  const titles = ["El río como archivo vivo", "Las manos que abren el mercado", "Una cancha después del colegio", "Cafés donde nace una ciudad", "Jóvenes que programan futuro", "La tambora que junta generaciones", "Turismo lento en bicicleta", "Costureras del clima cálido", "Voluntariado que acompaña la vejez", "La nueva mesa del bocachico"];
  const cats = ["Historia local", "Comunidad", "Deporte", "Emprendimiento", "Tecnología", "Cultura", "Turismo", "Moda", "Impacto Social", "Gastronomía"];
  return { id: index + 1, title: titles[index], slug: titles[index].toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g, "").replace(/[^a-z0-9]+/g, "-").replace(/(^-|-$)/g, ""), author: ["Redacción Hecho", "María del Río", "Juan Puerto"][index % 3], category: cats[index], coverImage: image(["photo-1500530855697-b586d89ba3ee", "photo-1488459716781-31db52582fe9", "photo-1526232761682-d26e03ac148e", "photo-1509042239860-f550ce710b93", "photo-1516321318423-f06f85e504b3", "photo-1514525253161-7a46d19cd819", "photo-1485965120184-e220f721d03e", "photo-1496747611176-843222e1e57c", "photo-1544027993-37dbfe43562a", "photo-1559847844-5315695dadae"][index]), excerpt: "Una crónica breve sobre personas, lugares y oficios que revelan el carácter comunitario de La Dorada.", content: "La Dorada se reconoce en sus gestos cotidianos: una puerta abierta al mediodía, una mesa compartida, una conversación que empieza con el clima y termina en una idea para el barrio. Esta historia documenta una iniciativa que no busca titulares, sino permanencia. Entre el río Magdalena, la estación y los comercios, aparecen personas que trabajan con paciencia para que la ciudad se mire con orgullo.", readingTime: 5 + (index % 5), featured: index < 4, createdAt: `2026-0${(index % 6) + 1}-1${index % 9}` };
});

export const podcastEpisodes = Array.from({ length: 8 }, (_, index) => ({ id: index + 1, title: `Episodio ${index + 1}: Voces que hacen ciudad`, slug: `voces-que-hacen-ciudad-${index + 1}`, guestName: ["Laura Castaño", "Andrés Ríos", "Natalia Gómez", "Mónica Salazar"][index % 4], category: categories[index % categories.length], summary: "Conversación sobre creación local, comunidad y los aprendizajes de emprender desde La Dorada.", spotifyUrl: "https://open.spotify.com/embed/episode/0", youtubeUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ", imageUrl: image("photo-1590602847861-f357a9332bbc"), highlights: ["Hacer ciudad empieza por escuchar.", "La colaboración reduce distancias.", "El orgullo local también se diseña."], projectId: (index % 6) + 1, createdAt: `2026-02-${10 + index}` }));

export const events = Array.from({ length: 10 }, (_, index) => ({ id: index + 1, title: ["Festival del Río", "Mercado de Emprendedores", "Taller de Crónica Local", "Rodada al Atardecer", "Noche de Tambora", "Feria de Servicios", "Cine al Parque", "Encuentro Tech", "Muestra Gastronómica", "Jornada de Voluntariado"][index], slug: `evento-${index + 1}`, date: `2026-0${(index % 6) + 6}-${String(8 + index).padStart(2, "0")}`, time: `${8 + (index % 10)}:00`, location: ["Malecón", "Parque Santander", "Biblioteca Municipal", "Plaza de Mercado"][index % 4], organizer: ["Colectivo local", "Hecho en La Dorada", "Casa Tambora"][index % 3], category: ["Cultura", "Comercio", "Educación", "Deporte"][index % 4], description: "Actividad abierta para encontrarse, aprender y celebrar lo que está pasando en la ciudad.", imageUrl: image("photo-1492684223066-81342ee5ff30"), whatsapp: "+573001112233", externalLink: "https://hechoenladorada.co" }));

export const indicators = Array.from({ length: 20 }, (_, index) => ({ id: index + 1, title: ["Población estimada", "Empresas registradas", "Visitantes mensuales", "Procesos culturales", "Instituciones educativas"][index % 5], value: ["78.000", "3.240", "+12%", "46", "28"][index % 5], category: ["Población", "Empresas", "Turismo", "Cultura", "Educación"][index % 5], description: "Indicador demo editable desde el panel administrador para lectura editorial del territorio.", source: "Dato demo / actualizar con fuente oficial", trend: [8, 14, 11, 19, 24, 21].slice(0, 4 + (index % 3)) }));

export const opportunities = Array.from({ length: 10 }, (_, index) => ({ id: index + 1, title: ["Buscamos barista", "Voluntarios para lectura", "Proveedor de empaques", "Socio para ruta turística", "Diseñador freelance"][index % 5], category: ["Ofrezco empleo", "Voluntariado", "Busco proveedor", "Busco socio", "Ofrezco servicios"][index % 5], description: "Publicación comunitaria moderada para conectar necesidades y talentos locales.", contactName: ["Equipo local", "Red comunitaria"][index % 2], contactPhone: "+573001112233", contactEmail: "hola@hechoenladorada.co", status: index % 3 === 0 ? "Pendiente" : "Publicada", createdAt: `2026-03-${10 + index}` }));
