import type { Metadata } from "next";
import { notFound } from "next/navigation";
import { ExternalLink, Facebook, Instagram, MessageCircle, UserRound } from "lucide-react";
import { ProjectCard } from "@/components/cards";
import { Badge, SectionTitle } from "@/components/ui";
import { podcastEpisodes, projects } from "@/lib/data";

type Props = { params: Promise<{ slug: string }> };

export function generateStaticParams() { return projects.map((project) => ({ slug: project.slug })); }
export async function generateMetadata({ params }: Props): Promise<Metadata> { const { slug } = await params; const project = projects.find((p) => p.slug === slug); return { title: project?.name ?? "Proyecto", description: project?.shortDescription }; }

export default async function ProjectDetail({ params }: Props) {
  const { slug } = await params; const project = projects.find((p) => p.slug === slug); if (!project) notFound();
  const related = projects.filter((p) => p.category === project.category && p.id !== project.id).slice(0, 3);
  const episode = podcastEpisodes.find((item) => item.projectId === project.id);
  return <article><section className="mx-auto grid max-w-7xl gap-10 px-4 py-14 lg:grid-cols-[1.1fr_0.9fr]"><div><Badge>{project.category}</Badge><h1 className="mt-5 font-serif text-5xl font-black leading-tight md:text-7xl">{project.name}</h1><p className="mt-6 max-w-3xl text-xl leading-9 text-suave/70">{project.shortDescription}</p><div className="mt-8 grid gap-3 text-sm font-semibold text-suave/70 md:grid-cols-2"><span><UserRound size={16} className="mr-2 inline" />Fundador: {project.founderName}</span><span>Año de inicio: {project.startYear}</span><span>Ubicación: {project.location}</span><span>Destacado: {project.featured ? "Sí" : "No"}</span></div></div><img src={project.mainImage} alt="" className="h-[520px] w-full rounded-[3rem] object-cover shadow-editorial" /></section><section className="mx-auto grid max-w-7xl gap-10 px-4 py-8 lg:grid-cols-[1fr_340px]"><div className="editorial-prose rounded-[2.5rem] bg-white p-8 text-lg shadow-editorial"><h2>Historia completa</h2><p>{project.story}</p><blockquote className="my-8 border-l-4 border-dorado pl-6 font-serif text-3xl font-bold text-tierra">“{project.quote}”</blockquote><p>Esta ficha está pensada para crecer con galería, video destacado, episodio relacionado y enlaces sociales. En producción se alimenta desde Supabase y puede ser editada por administradores o editores.</p><div className="mt-8 grid gap-4 md:grid-cols-2">{project.gallery.map((image) => <img key={image} src={image} alt="" className="h-64 rounded-3xl object-cover" />)}</div></div><aside className="space-y-4"><div className="rounded-[2rem] bg-magdalena p-6 text-white shadow-editorial"><h3 className="font-serif text-2xl font-black">Conectar</h3><div className="mt-5 grid gap-3 text-sm"><a href={`https://wa.me/${project.whatsapp.replace(/\D/g, "")}`} className="flex items-center gap-2"><MessageCircle size={16} />WhatsApp</a><span className="flex items-center gap-2"><Instagram size={16} />{project.instagram}</span>{project.facebook && <span className="flex items-center gap-2"><Facebook size={16} />Facebook</span>}{project.website && <a href={project.website} className="flex items-center gap-2"><ExternalLink size={16} />Sitio web</a>}</div></div>{episode && <div className="rounded-[2rem] bg-white p-6 shadow-editorial"><h3 className="font-serif text-2xl font-black">Episodio relacionado</h3><p className="mt-3 text-suave/65">{episode.title}</p></div>}</aside></section>{related.length > 0 && <section className="mx-auto max-w-7xl px-4 py-14"><SectionTitle eyebrow="Relacionados" title="Más proyectos de esta categoría" /><div className="grid gap-6 md:grid-cols-3">{related.map((item) => <ProjectCard key={item.id} project={item} />)}</div></section>}</article>;
}
